import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'

interface Headprops {
  title: string;
}

export default function Header(props:Headprops) {
  
  return (
    <>
      <Head>
        <title>{props.title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  )
}
